# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

require "shellwords"

default_platform(:mac)

lane :mac do
    build_mac_app
    xcodebuild(
        export_archive: true,
        archive_path: "./build/Amethyst.xcarchive",
        export_path: "./build",
        export_options_plist: "./exportOptions.plist"
    )
end

desc "Build and launch Amethyst Dev.app; pass skip_launch:true to build only"
lane :dev do |options|
    project_root = File.expand_path("..", __dir__)
    derived_data_path = File.join(project_root, "build", "DerivedData")
    app_path = File.join(derived_data_path, "Build", "Products", "Debug Dev", "Amethyst Dev.app")

    xcodebuild(
        workspace: "Amethyst.xcworkspace",
        scheme: "Amethyst Dev",
        configuration: "Debug Dev",
        derivedDataPath: derived_data_path
    )

    UI.success("Built #{app_path}")

    skip_launch = ["1", "true", "yes"].include?(options[:skip_launch].to_s.downcase)
    sh("open -n #{app_path.shellescape}") unless skip_launch
end
